require 'money'
require 'money/bank/google_currency'
require 'csv'

def saveratetousd
  currency_array = []
  currency_array.push("AED")
  currency_array.push("AFN")
  currency_array.push("ALL")
  currency_array.push("AMD")
  currency_array.push("ANG")
  currency_array.push("AOA")
  currency_array.push("ARS")
  currency_array.push("AUD")
  currency_array.push("AWG")
  currency_array.push("AZN")
  currency_array.push("BAM")
  currency_array.push("BBD")
  currency_array.push("BDT")
  currency_array.push("BGN")
  currency_array.push("BHD")
  currency_array.push("BIF")
  currency_array.push("BMD")
  currency_array.push("BND")
  currency_array.push("BOB")
  currency_array.push("BRL")
  currency_array.push("BSD")
  currency_array.push("BTC")
  currency_array.push("BTN")
  currency_array.push("BWP")
  currency_array.push("BYR")
  currency_array.push("BZD")
  currency_array.push("CAD")
  currency_array.push("CDF")
  currency_array.push("CHF")
  currency_array.push("CLF")
  currency_array.push("CLP")
  #currency_array.push("CNH")
  currency_array.push("CNY")
  currency_array.push("COP")
  currency_array.push("CRC")
  currency_array.push("CUP")
  currency_array.push("CVE")
  currency_array.push("CZK")
  #currency_array.push("DEM")
  currency_array.push("DJF")
currency_array.push("DKK")
currency_array.push("DOP")
currency_array.push("DZD")
currency_array.push("EGP")
currency_array.push("ERN")
currency_array.push("ETB")
currency_array.push("EUR")
#currency_array.push("FIM")
currency_array.push("FJD")
currency_array.push("FKP")
#currency_array.push("FRF")
currency_array.push("GBP")
currency_array.push("GEL")
currency_array.push("GHS")
currency_array.push("GIP")
currency_array.push("GMD")
currency_array.push("GNF")
currency_array.push("GTQ")
currency_array.push("GYD")
currency_array.push("HKD")
currency_array.push("HNL")
currency_array.push("HRK")
currency_array.push("HTG")
currency_array.push("HUF")
currency_array.push("IDR")
#currency_array.push("IEP")
currency_array.push("ILS")
currency_array.push("INR")
currency_array.push("IQD")
#currency_array.push("IRR")
currency_array.push("ISK")
#currency_array.push("ITL")
currency_array.push("JMD")
currency_array.push("JOD")
currency_array.push("JPY")
currency_array.push("KES")
currency_array.push("KGS")
currency_array.push("KHR")
currency_array.push("KMF")
currency_array.push("KPW")
currency_array.push("KRW")
currency_array.push("KWD")
currency_array.push("KYD")
currency_array.push("KZT")
currency_array.push("LAK")
currency_array.push("LBP")
currency_array.push("LKR")
currency_array.push("LRD")
currency_array.push("LSL")
currency_array.push("LTL")
currency_array.push("LVL")
currency_array.push("LYD")
currency_array.push("MAD")
currency_array.push("MDL")
currency_array.push("MGA")
currency_array.push("MKD")
currency_array.push("MMK")
currency_array.push("MNT")
currency_array.push("MOP")
currency_array.push("MRO")
currency_array.push("MUR")
currency_array.push("MVR")
currency_array.push("MWK")
currency_array.push("MXN")
currency_array.push("MYR")
currency_array.push("MZN")
currency_array.push("NAD")
currency_array.push("NGN")
currency_array.push("NIO")
currency_array.push("NOK")
currency_array.push("NPR")
currency_array.push("NZD")
currency_array.push("OMR")
currency_array.push("PAB")
currency_array.push("PEN")
currency_array.push("PGK")
currency_array.push("PHP")
#currency_array.push("PKG")
currency_array.push("PKR")
currency_array.push("PLN")
currency_array.push("PYG")
currency_array.push("QAR")
currency_array.push("RON")
currency_array.push("RSD")
currency_array.push("RUB")
currency_array.push("RWF")
currency_array.push("SAR")
currency_array.push("SBD")
currency_array.push("SCR")
currency_array.push("SDG")
currency_array.push("SEK")
currency_array.push("SGD")
currency_array.push("SHP")
currency_array.push("SLL")
currency_array.push("SOS")
currency_array.push("SRD")
currency_array.push("STD")
currency_array.push("SVC")
currency_array.push("SYP")
currency_array.push("SZL")
currency_array.push("THB")
currency_array.push("TJS")
#currency_array.push("TMT")
currency_array.push("TND")
currency_array.push("TOP")
currency_array.push("TRY")
currency_array.push("TTD")
currency_array.push("TWD")
currency_array.push("TZS")
currency_array.push("UAH")
currency_array.push("UGX")
currency_array.push("USD")
currency_array.push("UYU")
currency_array.push("UZS")
currency_array.push("VEF")
#currency_array.push("VND")
currency_array.push("VUV")
currency_array.push("WST")
currency_array.push("XAF")
currency_array.push("XCD")
#currency_array.push("XDR")
currency_array.push("XOF")
currency_array.push("XPF")
currency_array.push("YER")
currency_array.push("ZAR")
currency_array.push("ZMK")
currency_array.push("ZMW")
  currency_array.push("ZWL")
Money::Bank::GoogleCurrency.ttl_in_seconds = 3600
bank = Money::Bank::GoogleCurrency.new
  CSV.open("/root/myApp/config/ratetousd.txt", "w:UTF-8", {:col_sep => " "}) { |csv|
          currency_array.each do |curr|
            ratetousdvalue = bank.get_rate(curr, :USD).to_f
            csv << [curr, ratetousdvalue]
          end
          #csv << ["CNH", ]
          #csv << ["DEM", ]
          #csv << ["FIM", ]
          #csv << ["FRF", ]
          #csv << ["IEP", ]
          #csv << ["IRR", ]
          #csv << ["ITL", ]
          #csv << ["PKG", ]
          #csv << ["TMT", ]
          #csv << ["VND", ]
          #csv << ["XDR", ]
      }

  # copy to sfs dev
  #`sshpass -p 'buncha11' scp -o StrictHostKeychecking=no /root/myApp/config/ratetousd.txt lumbarunner@ec2-54-74-6-249.eu-west-1.compute.amazonaws.com:/home/lumbarunner/apps/SmartFoxServer_2X/SFS2X/data/lumba/core`
  # copy to sfs prod
  #`sshpass -p 'buncha11' scp -o StrictHostKeychecking=no /root/myApp/config/ratetousd.txt lumbarunner@ec2-54-228-106-202.eu-west-1.compute.amazonaws.com:/home/lumbarunner/apps/SmartFoxServer_2X/SFS2X/data/lumba/core`
  #`sshpass -p 'buncha11' scp -o StrictHostKeychecking=no /root/myApp/config/ratetousd.txt lumbarunner@ec2-176-34-79-231.eu-west-1.compute.amazonaws.com:/home/lumbarunner/apps/SmartFoxServer_2X/SFS2X/data/lumba/core`
end

saveratetousd
puts "done"
